apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpp-service
  namespace: energy-fetcher
  labels:
    app: myapp
    language: cpp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      language: cpp
  template:
    metadata:
      labels:
        app: myapp
        language: cpp
    spec:
      containers:
      - name: cpp-container
        image: yourregistry/myapp-cpp:latest
        env:
        - name: SCRIPT
          value: "code" # Change to "simple_code" if needed
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"