apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-service
  namespace: energy-fetcher
  labels:
    app: go-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-service
  template:
    metadata:
      labels:
        app: go-service
    spec:
      containers:
      - name: go-container
        image: yourregistry/myapp-go:latest
        env:
        - name: SCRIPT
          value: "code" # Change to "simple_code" as needed
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
