apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-service
  namespace: energy-fetcher
  labels:
    app: myapp
    language: go
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      language: go
  template:
    metadata:
      labels:
        app: myapp
        language: go
    spec:
      containers:
      - name: go-container
        image: myapp-go:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: SCRIPT
          value: "code" # Change to "simple_code" if needed
