apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-service
  namespace: energy-fetcher
  labels:
    app: python-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-service
  template:
    metadata:
      labels:
        app: python-service
    spec:
      containers:
      - name: python-container
        image: yourregistry/myapp-python:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
