apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-service
  namespace: energy-fetcher
  labels:
    app: myapp
    language: python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      language: python
  template:
    metadata:
      labels:
        app: myapp
        language: python
    spec:
      containers:
      - name: python-container
        image: yourregistry/myapp-python:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
